### Безпровідний вмикач Васі 158d0004650116 (single, double, long, both, double_both, long_both)
#1: Left single click
#- alias: wireless_master_binary_single_left_click
#  trigger:
#    platform: event
#    event_type: xiaomi_aqara.click
#    event_data:
#      entity_id: binary_sensor.wall_switch_left_158d0004650116
#      click_type: single
#  action:
#    - service: light.turn_on
#      data:
#        entity_id: light.yeelight_master_lamp
#2: Right single click
#- alias: wireless_master_binary_single_right_click
#  trigger:
#    platform: event
#    event_type: xiaomi_aqara.click
#    event_data:
#      entity_id: binary_sensor.wall_switch_right_158d0004650116
#      click_type: single
#  action:
#    - service: light.turn_off
#      data:
#        entity_id: light.yeelight_master_lamp
#3: Left long click
- alias: wireless_master_binary_long_left_click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0004650116
      click_type: long
  action:
    - service: switch.toggle
      data:
        entity_id: switch.wall_switch_right_158d0001dc2c2e
#4: Right long click
- alias: wireless_master_binary_long_right_click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d0004650116
      click_type: long
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_pc_switch
#5: Left double click
- alias: wireless_master_binary_double_left_click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0004650116
      click_type: double
  action:
    - service: script.turn_on_pc
## 6: Right double click
- alias: wireless_master_binary_double_right_click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d0004650116
      click_type: double
  action:
    - service: script.turn_off_pc
#7: Both single click
- alias: wireless_master_binary_long_both_click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_both_158d0004650116
      click_type: both
  action:
    - service: script.turn_off_all
