title: Mothership
views:
  - !include lovelace/home.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/internet.yaml
  - !include lovelace/system.yaml
  - !include lovelace/automation.yaml
  - !include lovelace/stat.yaml
