- platform: history_stats
  name: total_time_nergal
  entity_id: device_tracker.nergal
  state: 'home'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
- platform: history_stats
  name: total_time_nergal
  entity_id: device_tracker.tv
  state: 'home'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'