## Create Sensor for Display in UI
- platform: template
  sensors:
    skochko:
      friendly_name: "Вася"
      value_template: >-
        {% if is_state('device_tracker.pixel_5', 'home') %}
          Вдома
        {% elif is_state('device_tracker.pixel_5', 'work') %}
         На роботі
        {% elif is_state('device_tracker.pixel_5', 'lviv_center') %}
         У центрі
        {% elif is_state('device_tracker.pixel_5', 'lviv') %}
         Львів
        {% else %}
          Невідомо
        {% endif %}
      entity_picture_template: >-
        {% if is_state('device_tracker.pixel_5', 'work') %}
          /local/photos/skochko_at_work.jpg
        {% else %}
          /local/photos/skochko.jpg
        {% endif %}
    battery_skochko:
      friendly_name: ""
      value_template: "{{states('sensor.pixel_5_battery_level')}}"
      unit_of_measurement: "%"
      device_class: battery
### Viktoriia
    viktoriia:
      friendly_name: "Віка"
      value_template: >-
        {% if is_state('device_tracker.oneplus_a6000', 'home') %}
          Вдома
        {% elif is_state('device_tracker.oneplus_a6000', 'lviv_center') %}
         у центрі
        {% elif is_state('device_tracker.oneplus_a6000', 'lviv') %}
         Львів
        {% else %}
          Невідомо
        {% endif %}
      entity_picture_template: >-
        {% if is_state('device_tracker.oneplus_a6000', 'work') %}
          /local/photos/viktoriia.jpg
        {% else %}
          /local/photos/viktoriia.jpg
        {% endif %}
    battery_viktoriia:
      friendly_name: ""
      value_template: "{{states('sensor.oneplus_a6000_battery_level')}}"
      unit_of_measurement: "%"
      device_class: battery
