# Lun Misto AQI
- platform: rest
  name: lviv_shevchenka_aqi
  resource: https://misto.lun.ua/api/air/v1/public/data/
  value_template: >-
    {% set station = '161' %}
    {# #}
    {% macro aqi(aqihigh, aqilow, conchigh, conclow, conc) -%}
      {{ (aqilow + (conc - conclow) * (aqihigh - aqilow) / (conchigh - conclow)) | round }}
    {%- endmacro %}
    {# #}
    {% for sensor in value_json %}
      {% if sensor.station.name == station %}
        {% set conc = sensor.particles[2].pm25 %}
        {% if conc >= 0 and conc < 12 %}
            {{ aqi(50, 0, 12, 0, conc) }}
        {% elif conc >= 12 and conc < 35.5 %}
            {{ aqi(100, 51, 35.5, 12, conc) }}
        {% elif conc >= 35.5 and conc < 55.5 %}
            {{ aqi(150, 101, 55.5, 35.5, conc) }}
        {% elif conc >= 55.5 and conc < 150 %}
            {{ aqi(200, 151, 150.5, 55.5, conc) }}
        {% elif conc >= 150 and conc < 250.5 %}
            {{ aqi(300, 201, 250.5, 150.5, conc) }}
        {% elif conc >= 250.5 and conc < 350.5 %}
            {{ aqi(400, 301, 350.5, 250.5, conc) }}
        {% elif conc >= 350.5 and conc < 500.5 %}
            {{ aqi(500, 401, 500.5, 350.5, conc) }}
        {% else %}
            unknown
        {% endif %}
      {% endif %}
    {% endfor %}
  scan_interval: 1800 # every 2 minutes
  json_attributes_path: "$.[?(@.station.name=='161')].particles[2]"
  json_attributes:
    - pm25
    - pm10
    - pm100

# Lun Misto Sensors
- platform: template
  sensors:
    shevchenka_air_quality:
      value_template: >-
        {{ state_attr('sensor.lviv_shevchenka_aqi', 'pm25') | round() }}
