##########################
- alias: kitchen_morning_airing
  trigger:
    - platform: time
      at: input_datetime.morning_airing
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_kitchen_fan_switch
    - delay: "00:{{ states('input_select.minutes') | int }}:00"
    - service: switch.turn_off
      data:
        entity_id: switch.broadlink_kitchen_fan_switch
##########################
- alias: kitchen_night_airing
  trigger:
    - platform: time
      at: input_datetime.evening_airing
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_kitchen_fan_switch
    - delay: '01:00:00'
    - service: switch.turn_off
      data:
        entity_id: switch.broadlink_kitchen_fan_switch
##########################
- alias: kitchen_motion_airing
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002b4745b
    to: 'on'
  condition:
    - condition: state
      entity_id: switch.broadlink_kitchen_fan_switch
      state: 'off'
    - condition: time
      after: '10:00:00'
    - condition: time
      before: '23:00:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.broadlink_kitchen_fan_switch
    - delay: '01:00:00'
    - service: switch.turn_off
      data:
        entity_id: switch.broadlink_kitchen_fan_switch
