##########################
- alias: motion_led
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002b4745b
    to: 'on'
  condition:
    - condition: sun
      after: sunset
      before_offset: '02:00:00'
    - condition: time
      before: '23:45:00'
    - condition: state
      entity_id: light.lights_kitchen
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lights_kitchen
        transition: 6
    - service: switch.turn_on
      data:
        entity_id: switch.christmas_tree_switch
##########################
- alias: Motion Sensor Lights Off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002b4745b
      to: 'off'
      for:
        minutes: 30
  action:
    - service: light.turn_off
      data:
        entity_id: light.lights_kitchen
        transition: 10
##########################
- alias: led_off_on_midnight
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.lights_kitchen
    - service: switch.turn_off
      data:
        entity_id: switch.christmas_tree_switch

