- alias: shower_night_airing
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.wall_switch_left_158d00016c31cf
    - delay: '00:30:00'
    - service: switch.turn_off
      data:
        entity_id: switch.wall_switch_left_158d00016c31cf

#Автоматично вимкнути провітрювання
- alias: turn_off_shower_airing
  trigger:
    platform: state
    entity_id: switch.wall_switch_left_158d00016c31cf
    to: 'on'
    from: 'off'
  action:
    - delay: '01:00:00'
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d00016c31cf
