- alias: shower_morning_airing
  trigger:
    - platform: time
      at: input_datetime.morning_airing
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.wall_switch_left_158d00016c31cf
    - delay: '00:30:00'
    - service: switch.turn_off
      data:
        entity_id: switch.wall_switch_left_158d00016c31cf
##########################
- alias: shower_night_airing
  trigger:
    - platform: time
      at: input_datetime.evening_airing
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.wall_switch_left_158d00016c31cf
    - delay: '00:30:00'
    - service: switch.turn_off
      data:
        entity_id: switch.wall_switch_left_158d00016c31cf
##########################
- alias: auto_turn_off_shower_airing
  trigger:
    platform: state
    entity_id: switch.wall_switch_left_158d00016c31cf
    to: 'on'
    from: 'off'
  action:
    - delay: '01:00:00'
    - service: switch.turn_off
      entity_id: switch.wall_switch_left_158d00016c31cf



# ##########################
# - alias: сorridor_left_key
#   trigger:
#     platform: state
#     entity_id: switch.wall_switch_right_158d00016c31cf
#     to: 'off'
#     from: 'on'

#   action:
#     - service: media_player.media_play
#       data:
#         entity_id: media_player.alexa

# ##########################
# - alias: сorridor_left_key
#   trigger:
#     platform: state
#     entity_id: switch.wall_switch_right_158d00016c31cf
#     to: 'off'
#     from: 'on'

#   action:
#     - service: media_player.media_pause
#       data:
#         entity_id: media_player.alexa
